name: ci

on:
  push:
    branches: [master]
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go 🦋
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build 🚀
        run: bash ./scripts/build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: output/tnote.*

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            output/tnote.*

      # Prepare Docker Image Tags
      - name: Docker meta 🐳
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            shalldie/tnote
          tags: |
            type=semver,pattern={{raw}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      # Set up Docker Buildx
      - name: Set up Docker Buildx 🐳
        uses: docker/setup-buildx-action@v2

      # 登陆 Docker Hub
      - name: Login Docker Hub 🐳🐳
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PSW }}

      # 构建并推送 docker 镜像
      - name: Build & Push Docker Image 🐳🐳🐳
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
